# Site settings
title: Nexusrex's Gamedev Corner
description: >-
  A small Github Pages blog to share gamedev-related notes and thoughts

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock